name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Build and Push Docker Images
        run: |
          docker build -t johnsmith/my-frontend:frontend-v1 ./frontend
          docker build -t johnsmith/my-backend:backend-v1 ./backend
          docker push johnsmith/my-frontend:frontend-v1
          docker push johnsmith/my-backend:backend-v1

  deploy:
    needs: build_and_push
    runs-on: ubuntu-latest
    steps:
      - name: Configure kubectl with EKS
        run: |
          aws eks update-kubeconfig --region us-east-1 --name my-cluster

      - name: Deploy Kubernetes Manifests
        run: |
          kubectl apply -f k8s/
